// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `copy_images_from_dir`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `copy_mil_images`

class MddHelper {
  /// MDD file version
  final String version;

  /// MDD release date
  final String releaseDate;

  /// MDD release remarks
  final String? remarks;

  /// MDD release DOI
  final String? doi;

  /// MDD main data
  final List<String> mddData;

  /// Synonyms data
  final List<String> synData;

  const MddHelper({
    required this.version,
    required this.releaseDate,
    this.remarks,
    this.doi,
    required this.mddData,
    required this.synData,
  });

  static Future<MddHelper> parse({required List<int> bytes}) =>
      RustLib.instance.api.crateApiParserMddHelperParse(bytes: bytes);

  static Future<MddHelper> parseMddZip({required String zipPath}) =>
      RustLib.instance.api.crateApiParserMddHelperParseMddZip(zipPath: zipPath);

  @override
  int get hashCode =>
      version.hashCode ^
      releaseDate.hashCode ^
      remarks.hashCode ^
      doi.hashCode ^
      mddData.hashCode ^
      synData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MddHelper &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          releaseDate == other.releaseDate &&
          remarks == other.remarks &&
          doi == other.doi &&
          mddData == other.mddData &&
          synData == other.synData;
}

class MilHelper {
  final String milVersion;
  final String milData;

  const MilHelper({
    required this.milVersion,
    required this.milData,
  });

  static Future<String> extractMilVersion({required String path}) =>
      RustLib.instance.api.crateApiParserMilHelperExtractMilVersion(path: path);

  static Future<MilHelper> parseMilData(
          {required String tarPath, required String dbPath}) =>
      RustLib.instance.api.crateApiParserMilHelperParseMilData(
          tarPath: tarPath, dbPath: dbPath);

  @override
  int get hashCode => milVersion.hashCode ^ milData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MilHelper &&
          runtimeType == other.runtimeType &&
          milVersion == other.milVersion &&
          milData == other.milData;
}
