// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MddHelper {
  /// MDD file version
  final String version;

  /// MDD release date
  final String releaseDate;

  /// MDD main data
  final List<String> mddData;

  /// Synonyms data
  final List<String> synData;

  const MddHelper({
    required this.version,
    required this.releaseDate,
    required this.mddData,
    required this.synData,
  });

  static Future<MddHelper> parse({required List<int> bytes}) =>
      RustLib.instance.api.crateApiParserMddHelperParse(bytes: bytes);

  @override
  int get hashCode =>
      version.hashCode ^
      releaseDate.hashCode ^
      mddData.hashCode ^
      synData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MddHelper &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          releaseDate == other.releaseDate &&
          mddData == other.mddData &&
          synData == other.synData;
}
