name: test

on: push

jobs:
  check:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Check sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter analyze

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Extract MDD data
        working-directory: db/data
        run: |
          curl -L -o MDD.zip https://github.com/mammaldiversity/mammaldiversity.github.io/raw/master/assets/data/MDD.zip
          mdd zip -i MDD.zip

      - name: Run flutter test
        uses: subosito/flutter-action@v2
      - run: flutter test

      - name: Run rust test
        working-directory: mdd_api
        run: cargo test
