name: test

on: push

jobs:
  check:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: Check sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install mil-kit
        run: pip install mil-kit

      - name: Install uv
        run: pip install uv

      - name: Test tools (svg_generator)
        working-directory: tools/svg_generator
        run: uv run pytest

      - name: Install MDD CLI
        run: cargo install mdd_api

      - name: Extract MDD data
        working-directory: assets/data
        run: |
          curl -L -o MDD.zip https://github.com/mammaldiversity/mammaldiversity.github.io/raw/master/assets/data/MDD.zip
          mdd unpack -i MDD.zip

      - name: Extract MIL data
        working-directory: assets/data
        run: |
          MIL_URL=$(curl -s https://api.github.com/repos/mammaldiversity/asm-mil/releases/latest \
            | grep -o '"browser_download_url": *"[^"]*\.tar\.gz"' \
            | grep -o 'https://[^"]*')
          MIL_FILENAME=$(basename "$MIL_URL")
          MIL_DIRNAME="${MIL_FILENAME%.tar.gz}"
          echo "Downloading MIL data from $MIL_URL"
          curl -L -o "$MIL_FILENAME" "$MIL_URL"
          echo "Extracting $MIL_FILENAME to $MIL_DIRNAME"
          tar -xzf "$MIL_FILENAME"
          MDD_FILE=$(ls MDD/MDD_v*.csv)
          MIL_DATE="${MIL_DIRNAME#mil-v}"
          MIL_BASE_DATE=$(echo "$MIL_DATE" | sed 's/\.[0-9]*$//')
          echo "MIL_DIRNAME=$MIL_DIRNAME" >> $GITHUB_ENV
          echo "Processing MIL data using MDD file $MDD_FILE"
          mil-kit mdd \
            --mil-file "$MIL_DIRNAME/metadata/mil-$MIL_BASE_DATE.xlsx" \
            --mdd-file "$MDD_FILE" \
            --mil-img-dir "$MIL_DIRNAME/images-540px-webp" \
            --output mil

      - name: Copy MIL images to assets
        working-directory: assets/data
        run: |
          IMAGES_DIR="$MIL_DIRNAME/images-540px-webp"
          mkdir -p ../mil-images
          find "$IMAGES_DIR" -name "*.webp" -exec mv {} ../mil-images/ \;

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: |
          flutter pub get
          flutter analyze

      - name: Run flutter test
        uses: subosito/flutter-action@v2
      - run: flutter test

      - name: Run rust test
        working-directory: mdd_api
        run: cargo test
